[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

[[plugins]]
  package = "@sentry/netlify-build-plugin"

[context.production.environment]
  VITE_API_URL = "https://api.irmaosfarias.com"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_SENTRY_ENVIRONMENT = "production"
  VITE_PERFORMANCE_MONITORING = "true"
  VITE_ERROR_MONITORING = "true"
  VITE_LOG_LEVEL = "error"

[context.staging.environment]
  VITE_API_URL = "https://staging-api.irmaosfarias.com"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_SENTRY_ENVIRONMENT = "staging"
  VITE_PERFORMANCE_MONITORING = "true"
  VITE_ERROR_MONITORING = "true"
  VITE_LOG_LEVEL = "info"

[context.deploy-preview.environment]
  VITE_API_URL = "https://staging-api.irmaosfarias.com"
  VITE_ENABLE_ANALYTICS = "false"
  VITE_SENTRY_ENVIRONMENT = "preview"
  VITE_PERFORMANCE_MONITORING = "true"
  VITE_ERROR_MONITORING = "true"
  VITE_LOG_LEVEL = "debug"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://*.sentry.io;"